name = "BaseSci"
author = "jordy_vogeltjes"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96c38f8acc588bdaa9ee5383dd5fb5feb9958d6be4ae911c6c218c3cb0efc672"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
