name = "BaseSci"
author = "jordy_vogeltjes"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63c9b9e2d83e0b84228b1c13afe5ae20741ad8de2b9b834f4a0668065cf3c549"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
