name = "BaseSci"
author = "jordy_vogeltjes"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "068f0d8c88c2498f2877b31ae0281504a17cab2edc9c78aca23e2136ce13d80b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
