name = "BaseSci"
author = "jordy_vogeltjes"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5dc6aa456a14180bf6c1507125fb6d2ea9d2cfa222103a422d32b3f2cee7e63"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
