name = "BaseSci"
author = "jordy_vogeltjes"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1848428aa185198f7e799ad3a9df56de07c12387d2b89b056b0df4e206bfc9a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
