name = "BaseSci"
author = "jordy_vogeltjes"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4a800a95af0c3203dbc5a4f76c7ab2204f1cfa5ed56e8aa4cdc758cfa559240"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5"]
